version: '3'
services: 
  mongo:
    container_name: mongo-dev
    restart: always
    image: mongo
    env_file: .env
    environment:
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_USER}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./mongoUser.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - ./mymongodb:/data/db
    ports:
      - '27017:27017'
  api:
    image: node:10.5.0
    env_file: .env
    environment:
      NODE_ENV: development
    volumes:
      - ./api:/app
    working_dir: /app
    command: npm run dev
    ports:
      - 5000:5000
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_USER=${MONGO_USER}
      - ISDEV=HI
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
  client:
    container_name: dev-client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
    - './client:/app'
    - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  nginx:
    restart: always
    depends_on:
      - mongo
      - api
      - client
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'